export const configFileName = "bshopify.config.mjs";

export const recommendedScripts: Record<string, string> = {
  dev: "bshopify app dev",
  deploy: "bshopify app deploy",
};

export const runnerConfigTemplate = `// bshopify runner config
// This file controls how bshopify selects Shopify app config files and how
// extension injections behave during dev and deploy.

export default {
  // --- App: Shopify app config files by environment ---
  configFiles: {
    dev: "shopify.app.dev.toml",
    test: "shopify.app.test.toml",
    production: "shopify.app.production.toml",
  },

  // --- Extension: injection behavior ---
  // Fail when an injection plan leaves template placeholders unresolved.
  failOnUnresolvedPlaceholders: true,
};
`;
export const legacyPreCommitGuardCommand = "bshopify guard";
export const legacyPreCommitGuardEndMarker = "# bshopify guard end";
export const legacyPreCommitGuardStartMarker = "# bshopify guard start";
export const preCommitGuardCommand = `if [ -x "./node_modules/.bin/bshopify" ]; then
  ./node_modules/.bin/bshopify app guard
else
  bshopify app guard
fi`;
export const preCommitGuardEndMarker = "# bshopify app guard end";
export const preCommitGuardStartMarker = "# bshopify app guard start";

export const preCommitHookTemplate = `#!/usr/bin/env sh
set -e

${preCommitGuardStartMarker}
${preCommitGuardCommand}
${preCommitGuardEndMarker}
`;

export const cleanFilterScriptName = ".bshopify/git-add-cleaner.js";
export const cleanFilterCommand = "node .bshopify/git-add-cleaner.js";
export const cleanFilterSmudgeCommand = "node .bshopify/git-add-cleaner.js --smudge";

export const gitattributesCliComment = "# bshopify cli";

/**
 * Standalone git clean/smudge filter written into the project's bshopify
 * state directory by `init`.
 *
 * The clean direction restores bshopify injection markers so `git add`
 * never stages temporary injected values; files without markers (including
 * binaries) pass through untouched. The smudge direction is the identity.
 * The script is gitignored (`.bshopify/`), so it is not carried in the repo:
 * `init` writes it on first setup and `init --update` replaces it whenever
 * the CLI template changes. The git filter command itself also lives in
 * local `.git/config` (set by `init`), so a fresh clone needs `init` either
 * way before the filter is active. It must stay dependency-free and
 * synchronous with `restoreInjectedMarkers` in
 * `src/app/runner/restore-markers.ts`.
 */
export const cleanFilterScript = String.raw`#!/usr/bin/env node
// Generated by bshopify (bshopify app init). Do not edit by hand.
// Restores bshopify injection markers when files are staged, so temporary
// injected values never enter the index. Files without valid markers pass
// through byte-for-byte (including binaries and non-UTF-8 text).
"use strict";

const markerBytes = Buffer.from("bshopify-restore:");
const markerPatterns = [
  /\/\* bshopify-restore:([A-Za-z0-9_-]+):(\d+):([0-9a-fA-F]{16}):([0-9a-fA-F-]+) \*\//g,
  /<!-- bshopify-restore:([A-Za-z0-9_-]+):(\d+):([0-9a-fA-F]{16}):([0-9a-fA-F-]+) -->/g,
  /\{\/\* bshopify-restore:([A-Za-z0-9_-]+):(\d+):([0-9a-fA-F]{16}):([0-9a-fA-F-]+) \*\/\}/g,
  /\{% comment %} bshopify-restore:([A-Za-z0-9_-]+):(\d+):([0-9a-fA-F]{16}):([0-9a-fA-F-]+) \{% endcomment %\}/g,
];

// 64-bit FNV-1a-style checksum over UTF-16 code units. Must stay identical
// to createValueChecksum in src/utils/markers.ts.
function createValueChecksum(value) {
  let hash = 0xcbf29ce484222325n;
  const prime = 0x100000001b3n;

  for (let index = 0; index < value.length; index += 1) {
    hash = BigInt.asUintN(64, (hash ^ BigInt(value.charCodeAt(index))) * prime);
  }

  return hash.toString(16).padStart(16, "0");
}

function findMarkers(content) {
  const markers = [];

  for (const pattern of markerPatterns) {
    pattern.lastIndex = 0;

    for (const match of content.matchAll(pattern)) {
      const fullText = match[0];
      const fullStart = match.index;
      markers.push({
        checksum: match[3],
        fullEnd: fullStart + fullText.length,
        fullStart,
        pattern: Buffer.from(match[1], "base64url").toString("utf8"),
        valueLength: Number(match[2]),
      });
    }
  }

  // Drop markers fully contained inside another marker's comment (the jsx
  // syntax also matches the block regex on its inner part).
  const sorted = markers.sort((left, right) => left.fullStart - right.fullStart);
  const unique = [];
  let lastFullEnd = 0;

  for (const marker of sorted) {
    if (marker.fullStart >= lastFullEnd) {
      unique.push(marker);
      lastFullEnd = marker.fullEnd;
    }
  }

  return unique;
}

function clean(content) {
  if (!content.includes("bshopify-restore:") || content.includes("\u0000")) {
    return content;
  }

  const markers = findMarkers(content);

  if (markers.length === 0) {
    return content;
  }

  let result = content;
  let consumedFrom = content.length;

  for (let index = markers.length - 1; index >= 0; index -= 1) {
    const marker = markers[index];

    // Skip markers inside a region already replaced by a marker to their
    // right (marker-like text inside an injected value).
    if (marker.fullStart >= consumedFrom) {
      continue;
    }

    const valueStart = marker.fullStart - marker.valueLength;

    if (valueStart < 0) {
      continue;
    }

    if (createValueChecksum(content.slice(valueStart, marker.fullStart)) !== marker.checksum) {
      continue;
    }

    result = result.slice(0, valueStart) + marker.pattern + result.slice(marker.fullEnd);
    consumedFrom = valueStart;
  }

  return result;
}

const smudge = process.argv.includes("--smudge");
const chunks = [];

process.stdin.on("data", (chunk) => {
  chunks.push(chunk);
});
process.stdin.on("end", () => {
  const input = Buffer.concat(chunks);

  // Files without markers (binaries, non-UTF-8 text, plain files) must pass
  // through byte-for-byte: never decode and re-encode them.
  if (smudge || !input.includes(markerBytes)) {
    process.stdout.write(input);
    return;
  }

  const text = input.toString("utf8");

  if (!Buffer.from(text, "utf8").equals(input)) {
    process.stdout.write(input);
    return;
  }

  process.stdout.write(clean(text));
});
process.stdin.on("error", () => {
  process.exit(1);
});
`;
