export type ShopifyCommandRunner = (args: string[]) => Promise<number | void>;

export interface DevOptions {
  configName?: string;
  cwd?: string;
  runShopifyCommand?: ShopifyCommandRunner;
  shopifyArgs?: string[];
}

export interface DeployOptions {
  configName?: string;
  confirmProduction?: boolean;
  cwd?: string;
  dryRun?: boolean;
  runShopifyCommand?: ShopifyCommandRunner;
  shopifyArgs?: string[];
  yes?: boolean;
}

/**
 * The config shape `bshopify.config.mjs` accepts, before defaults are
 * applied. Every field is optional: anything omitted falls back to the
 * internal defaults at load time, so a config with only the fields the
 * team cares about is valid.
 *
 * This is the type accepted by `defineConfig` for a Vite-style typed
 * default export when the package is installed in the project. The config
 * template generated by `init` inlines a self-contained JSDoc typedef of
 * the team-facing subset below instead, so global-only installs also get
 * editor hints without the project being able to resolve the package.
 */
export interface RunnerConfigInput {
  /** App: Shopify app config files by environment (key → root-relative `shopify.app*.toml`). */
  configFiles?: ConfigFileMap;
  /** Extension: custom env namespaces injected into the runner context. */
  envFiles?: EnvFilesConfig;
  /** Internal default (`__entry.js`): bshopify-managed entry file name. Kept loadable for backward compatibility. */
  entryFileName?: string;
  /** Internal default (`extensions`): directory that contains Shopify extension folders. Kept loadable for backward compatibility. */
  extensionsRoot?: string;
  /** Extension: fail when an injection plan leaves template placeholders unresolved. */
  failOnUnresolvedPlaceholders?: boolean;
  /** Internal default (`true`): add file-type-aware restore comments during dev. Kept loadable for backward compatibility. */
  restoreMarkers?: boolean;
}

/**
 * bshopify runner configuration loaded from `bshopify.config.mjs`.
 *
 * Only `configFiles`, `envFiles`, and `failOnUnresolvedPlaceholders` are
 * meant to be configured by the team. `extensionsRoot`, `entryFileName`, and
 * `restoreMarkers` are internal defaults: new projects do not expose them,
 * but existing configs may still override them for backward compatibility.
 */
export interface RunnerConfig {
  /** App: Shopify app config files by environment. */
  configFiles: ConfigFileMap;
  /** Extension: custom env namespaces injected into the runner context. */
  envFiles: EnvFilesConfig;
  /** Internal default: bshopify-managed entry file name. */
  entryFileName: string;
  /** Internal default: directory that contains Shopify extension folders. */
  extensionsRoot: string;
  /** Extension: fail when an injection plan leaves template placeholders unresolved. */
  failOnUnresolvedPlaceholders: boolean;
  /** Internal default: add file-type-aware restore comments during dev. */
  restoreMarkers: boolean;
}

/**
 * Custom env namespaces for extension injection, configured as
 * `envFiles` in `bshopify.config.mjs`: key → one or more root-relative
 * JSON/TOML file paths. Each key becomes its own field on the runner context
 * (e.g. `aEnv` → `ctx.aEnv`), with the referenced file contents merged.
 */
export interface EnvFilesConfig {
  [key: string]: string | string[];
}

export interface ConfigFileMap {
  [key: string]: string;
}

/**
 * The runtime context handed to app orchestration and to each extension's
 * `__entry` lifecycle. `configPath` / `env` / `appConfig` come from the
 * enabled Shopify app TOML; every additional key is a custom env namespace
 * injected from `bshopify.config.mjs` `envFiles` (key → merged file contents).
 */
export interface RunnerContextBase {
  /** Currently enabled Shopify app TOML file name (`configFiles.<env>` value). */
  configPath: string;
  /** The `configFiles` key of the current environment (e.g. `dev`, `test`, `production`). */
  env: string;
  /** Parsed contents of the TOML file, passed through as-is. */
  appConfig: Record<string, unknown>;
  /** Custom env namespaces injected from `envFiles` (key → merged contents). */
  [envNamespace: string]: unknown;
}

export interface FileTransaction {
  /** Restores every tracked injection and returns the paths of the restored files. */
  restore(): Promise<string[]>;
  writeFile(path: string, content: string, replacement: ReverseReplacement): Promise<void>;
}

export interface ReverseReplacement {
  marker?: string;
  pattern: string;
  value: string;
}

export interface TrackedFile {
  path: string;
  replacements: ReverseReplacement[];
}
