export { createCliProgram, runCli, runShopifyCommand } from "./main";
export { packageInfo } from "./utils/package-json";
export { clearProject, formatClearResult } from "./app/commands/clear";
export { deployProject } from "./app/commands/deploy";
export { devProject } from "./app/commands/dev";
export { formatInitResult, initProject } from "./app/commands/init";
export { defineConfig } from "./app/runner/config";

export type { CliDependencies, ProcessRunner, ShopifyCommandRunner } from "./main";
export type { PackageInfo } from "./utils/package-json";
export type { ClearOptions, ClearResult } from "./app/commands/clear/types";
export type { DeployOptions } from "./app/runner/types";
export type { DevOptions } from "./app/runner/types";
export type { InitCheck, InitOptions, InitResult } from "./app/commands/init/types";

// bshopify.config.mjs typing: the config template generated by `init`
// references RunnerConfigInput via JSDoc, and `defineConfig` offers the
// same hints with a Vite-style helper when the config imports the package.
export type { RunnerConfigInput } from "./app/runner/types";

// Extension entry lifecycle types: what `__entry.js` authors need to type
// their prepare / validate / beforeDeploy / afterDeploy / onError hooks.
// The generated entry template references these via JSDoc:
// `@type {import('@bestfulfill/bshopify').ExtensionLifecycle}`.
export type {
  ExtensionContext,
  ExtensionDeployResult,
  ExtensionInfo,
  ExtensionLifecycle,
  ExtensionPlanResult,
  InjectionPlan,
  ManagedEntry,
  PreparedExtensionPlan,
} from "./extension/types";
